# Generated by Django 3.0.1 on 2020-03-23 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200323_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='allbookings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_name', models.CharField(blank=True, max_length=50, null=True)),
                ('visiname', models.CharField(blank=True, default='NONE', max_length=50, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(blank=True, choices=[('allow', 'Allow'), ('occupied', 'Occupied')], default='allow', max_length=50)),
                ('car_number', models.CharField(blank=True, max_length=50, null=True)),
                ('Phonenumber', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
